### ISSUE TITLE
Add support for `example` for use in openapi documentation

### ISSUE THREAD

**Issue by matmar10** [chaliy/sequelize-json-schema#17]
https://swagger.io/docs/specification/adding-examples/

Example:

```
let Simple = sequelize.define('simple', {
  title: {
    type: Sequelize.STRING,
    example: '10 Shocking Things That Go Viral'
  },
  articleId: {
    type: Sequelize.INTEGER,
    example: 42
  },
  tags: {
    type: Sequelize.ARRAY(Sequelize.STRING),
    example: ['clickbait', 'viral', 'article']
  }
});

let def = definition(Simple);
/*
{
  "type": "object",
  "required": ["title", "articleId", "tags"],
  "properties": {
    "title": {
      "type": "string",
      "example": "10 Shocking Things That Go Viral"
    },
    "articleId": {
      "type": "integer",
      "example": 25
    },
    "tags": {
      "type": "array",
      "items": {
        "items": "string"
      },
      "example": ["title", "articleId", "tags"]
    }
  }
}
*/

```

**Comment by broofa** [comment]
Closing for a several reasons that mostly boil down to, "Needs better specification".

On the Sequelize side, it's not clear where we should pull examples from.  I'm not seeing any official API documentation for a `example`, `examples`, or `description` field.  (A `description` field is mentioned [here](https://sequelize.org/master/manual/models-definition.html), but not in actual API docs). 

On the JSON Schema side, `example` isn't a valid field either.  `examples` is (as of  [draft 6](https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-7.4)), but it has to be a valid JSON schema Object.
