### ISSUE TITLE
plz add sequelize comment.

### ISSUE THREAD

**Issue by AlfieriChou** [chaliy/sequelize-json-schema#20]
```javascript
id: {type: DataTypes.INTEGER, comment: 'id'}
```
this comment updated to description.
Now, schema properties field not description.

```javascript
{
  type: 'object',
  properties: {
    id: {
      type: 'integer',
      format: 'int32',
      description: 'id'
    }
  }
}
```

**Comment by broofa** [comment]
While I see docs for `description` [here](https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-7.2) in the JSON Schema spec, I'm not seeing anything for `comment` or `description` in the [Sequelize API docs for attribute definition](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-init).  `description` is mentioned [here](https://sequelize.org/master/manual/models-definition.html), but that looks like a copy/paste error.

I'm reluctant to support this until there's formal documentation in Sequelize that provide a canonical property (and property type) for comment/description information.

Closing for now, but with the suggestion that OP open a Feature Request with the Sequelize project for a `description` field.
