### ISSUE TITLE
Support for `defaultValue`

### ISSUE THREAD

**Issue by RickEyre** [chaliy/sequelize-json-schema#21]
It seems that columns that have a `defaultValue` defined are still listed as required in the JSON schema.

Is this correct?

**Comment by broofa** [comment]
FYI, I've just pushed a wholesale rewrite of this module as v2.0.0.  The current logic is that attributes with `allowNull` explicitly set to false are marked as required.  The code does not look at the `defaultValue` property.

**Comment by broofa** [comment]
This is a tricky issue, but I think the current (v2) behavior is correct.  We're generating schemas in the context of Sequelize, where "required" means "NOT NULL", and where a default value doesn't preclude explicitly setting a column to NULL later on.

I.e. NOT NULL means "required" in SQL, and default value behavior is independent of this.
