### ISSUE TITLE
Issues with JSON Schema format while compiling Schema in AJV

### ISSUE THREAD

**Issue by SandeepPamujula** [chaliy/sequelize-json-schema#9]
Hi,

Converted JSON schema is given to [AJV](https://www.npmjs.com/package/ajv) to validate user input. There are some issues with the schema generated using sequelize-json-schema while compiling it with AJV. 
for example:
{
    "incidentID": 0,
    "errorCode": 1254,
    "description": "unknown **format** \"int32\" is used in schema at path \"#/properties/id\""
}

where do we use this **format**? is there any plans to remove it?
FYI:
https://stackoverflow.com/questions/44878192/convert-sequelize-model-to-json-schema-for-user-input-validation

Regards,
Sandeep

**Comment by chaliy** [comment]
`format` is swagger extension to JSON Schema, `int32` is defined here https://github.com/OAI/OpenAPI-Specification/blob/master//versions/2.0.md#data-types . If your tool doesn't support swagger extensions, it probably should just ignore it.

**Comment by chaliy** [comment]
Ah, well, ajv supports its own `format` values https://www.npmjs.com/package/ajv#formats , and not all of them are compatible with swagger's definition. Honestly I do not know what to do here, neither swagger nor ajv are standard.
